CREATE DATABASE crudDB;
GRANT ALL PRIVILEGES ON DATABASE crudDB to postgres;
\c crudDB;


CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    post TEXT NOT NULL,
    likes INT NOT NULL DEFAULT 0
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(30) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    is_mod BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);